services:
  postgresql:
    image: bitnami/postgresql
    container_name: patient-assessment-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=patient-assessment-postgresql
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
 postgresql:
    driver: local
